### ISSUE TITLE
The Quick Start Next.js App Router Start a local dev server is duplicated

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/docs#6819] opened 2024-01-23 00:43 UTC
**Describe the bug**
Go to the quick start [Next.js App Router](https://docs.amplify.aws/gen2/start/quickstart/nextjs-app-router/#start-local-dev-server) section. The Start a local dev server shows twice.

**Expected behavior**
Section should only be in there once.

**Comment by katiegoines** [comment] 2024-01-25 17:54
Hi @ErikCH - I'm not able to reproduce this, are there specific circumstances when this occurs? Thanks!

**Comment by reesscot** [comment] 2024-02-07 23:03
Closing out as this was fixed.

**Closed as completed by reesscot** 2024-02-07 23:03 UTC
Labels: amplify/docs-engineering
