### ISSUE TITLE
"Connect API and database to the app" part

### ISSUE THREAD

**Issue by paulpacaud** [aws-amplify/docs#4743] opened 2022-10-24 00:37 UTC
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/angular)

**Feedback**:

When we follow the tutorial in this part, at the end we just get the following errors:

Error: src/app/restaurants/restaurants.component.ts:35:61 - error TS2339: Property 'subscribe' does not exist on type '(filter?: ModelSubscriptionRestaurantFilterInput | undefined) => Observable<SubscriptionResponse<Pick<__SubscriptionContainer, "onCreateRestaurant">>>'.

35     this.subscription = this.api.OnCreateRestaurantListener.subscribe(

                          ~~~~~~~~~~~~~~~

It comes from the fact that you really badly describe what we have to do in app.component.ts.. !!!!

**Comment by abdallahshaban557** [comment] 2022-10-24 22:55
Hello @paulpacaud  - can you please paste the end result of your app.component.ts file here?

Also - which version of the Amplify library are you using? you can check that from your package.json file

**Comment by Tenock** [comment] 2022-11-03 16:53
I am also having this issue. I'm currently using zen-observable-ts 0.8.21

Which version is compatible with Amplify? I've done a fresh npm install with no success.

**Comment by BrantDesu** [comment] 2022-11-09 21:43
> To solve in this case, you can remove the `zen-observable-ts` dependency from the client app's `package.json` file, delete the `package-lock.json` file and do a fresh `npm install`. `aws-amplify` dependency should download the compatible version of `zen-observable-ts` package which you can use in your client app.

Same problem here, did what you suggested with no success...
Here is a workaround using the `graphql/subscriptions.graphql` file as shown in the [docs](https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/js/)

```javascript
const subscription = API.graphql(
      graphqlOperation(subscriptions.onCreateRestaurant)
      // @ts-ignore:
    ).subscribe({// @ts-ignore:
      next: ({ provider, value }) => console.log({ provider, value }),
      // @ts-ignore:
      error: (error) => console.warn(error)
    });
```
Then, everytime you create a new `restaurant`, the data will be stored inside the `value` variable:

![image](https://user-images.githubusercontent.com/21161232/200946898-1ee61104-f589-4117-a72a-81694af285be.png)

Hope it has been helpful :)

**Comment by simon3073** [comment] 2022-12-17 01:26
Any resolution on this? Im also having the "subscribe does not exist on type issue"

**Comment by Tenock** [comment] 2022-12-23 18:13
Found a solution to this, thanks to this [post on StackOverflow](https://stackoverflow.com/questions/73375503/aws-amplify-and-angular-integration-getting-started-connect-api-and-database-t).
The Filter parameter, implemented automatically on queries for model directive definitions, is missing on the suggested documentation. Have to be set to undefined to match the subscription type to the response coming from graphQL.

`this.subscription = this.api.OnCreateRestaurantListener(undefined).subscribe( 
      (event: any) => {
        const newRestaurant = event.value.data.onCreateRestaurant;
        console.log(event.value.data.onCreateRestaurant);
        this.restaurants = [newRestaurant, ...this.restaurants];
      }
    );`

**Comment by Auston-Zhang** [comment] 2023-02-05 20:17
feel the same, unsure about if this code snippet should be in 

app.component.ts
or
restaurants.component.ts

sorry I'm very new to Angular but it would be super helpful.

and could AWS also provide a more complete code repo for us to refer to?

**Comment by cwomack** [comment] 2023-04-26 20:32
@paulpacaud, I wasn't able to reproduce the errors you experienced after running through the [Angular Getting Started Tutorial](https://docs.amplify.aws/start/q/integration/angular/) recently.  However, there were some errors found (as @Auston-Zhang stated) due to improper file references.  For anyone else following this issue, there was updates made to the example GraphQL schema as well that should prevent other Auth errors from showing (especially once Auth is implemented later in the tutorial steps).  These were likely due to the fact that the GraphQL API now operates on a "deny-by-default" principle if an authorization rule is not specifically configured. 

Once PR #5433 is merged, feel free to try this tutorial again and let me know if you run into the same steps!  Thank you @paulpacaud for opening this issue and for the additional context from others on this page.

**Closed** 2023-05-09 22:10 UTC
Labels: amplify/js, getting-started, p2
