### ISSUE TITLE
Switching platforms does not keep the same path

### ISSUE THREAD

**Issue by atierian** [aws-amplify/docs#6468] opened 2023-11-17 15:41 UTC
**Describe the bug**
Switching platforms in the **Choose your framework/language** dropdown does not maintain the URL path after `/{platform}`, even if it exists in the newly selected platform.

**To Reproduce**
1. Go to https://docs.amplify.aws/swift/build-a-backend/push-notifications/
2. Click on **Chose your framework/language** and select **Android** (or any other platform)
3. You are now on https://docs.amplify.aws/android/

**Expected behavior**
You should be on https://docs.amplify.aws/android/build-a-backend/push-notifications/
Switching from one platform to another should maintain the same path if it exists on the newly selected platform.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox and Safari

**Comment by reesscot** [comment] 2024-02-08 00:10
Hi @atierian,
Thank you for submitting this issue. It was a product decision to simplify the platform switcher in order to eliminate a source of numerous bugs in the previous implementation. It's not common to be switching between platforms when developing an application, so we feel the current behavior is sufficient. I will close this out as intended behavior.

**Comment by reesscot** [comment] 2024-04-30 17:41
Fixed by: https://github.com/aws-amplify/docs/pull/7339

**Closed by reesscot** 2024-04-30 17:41 UTC
Labels: amplify/docs-engineering
