### ISSUE TITLE
[missing-page]  Amplify CLI Export command

### ISSUE THREAD

**Issue by maBarabas** [aws-amplify/docs#4044] opened 2022-02-16 17:02 UTC
**Page**: [`https://docs.amplify.aws/usage/export-to-cdk/`](https://docs.amplify.aws/usage/export-to-cdk/)

**Feedback**:  This is linked in the readme for https://github.com/aws-amplify/amplify-cli-export-construct.

The correct page is https://docs.amplify.aws/cli/usage/export-to-cdk/.

**Comment by maBarabas** [comment] 2022-02-17 09:31
@calavera Could you please explain the incorrect-info label?

The link is a 404 for me, and it is referenced in https://github.com/aws-amplify/amplify-cli-export-construct/blob/main/README.md

**Comment by siegerts** [comment] 2022-03-14 17:08
Hi @maBarabas, I've opened a PR to fix the readme in the export construct repo. Closing this as the issue is with that project. 

https://github.com/aws-amplify/amplify-cli-export-construct/pull/33

**Closed as completed by siegerts** 2022-03-14 17:08 UTC
Labels: bug, amplify/cli, incorrect-info
