### ISSUE TITLE
User Attributes are coerced to boolean

### ISSUE THREAD

**Issue by cgardens** [aws-amplify/docs#1877] opened 2020-05-26 22:04 UTC
**Describe the bug**
Amplify coerces user attribute strings to booleans in an opaque manner. 

**To Reproduce**

1. Add a custom attribute in Cognito with type string.
2. Set the value of that attribute to "true" or "false"
3. `Auth.signin(<your user>)`
4. Inspect the returned user attributes. The value returned for the custom attribute with be `true` not `"true"`.

**Expected behavior**
Expect the original types of the Cognito to be returned (e.g. `"true"`) OR to document that this type coercion takes place.

**Code Snippet**
The function that causes this can be found [here](https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/Auth.ts#L1926-L1940). I haven't been able to figure out if there is a reason this type coercion needs to happen. In scanning the file, it doesn't appear to be necessary. 

**Summary**
This was confusing when I encountered it, especially because Cognito is so insistent that it does _not_ support custom attributes with type boolean. As "fixing" this behavior will require a breaking change, the best thing to do at this point might simply be to document it in the read me. 

I would have taken a crack at documenting it, but I couldn't find a sensible place to put it in the readme as user attributes are only mentioned in passing. If that's what you'd like though, would be happy to do that. Thanks!

**Comment by elorzafe** [comment] 2020-06-11 23:17
@cgardens I tried to reproduce your issue, but I couldn't update a custom attribute passing `true` or `false`.

Cognito documentation on [Custom attributes](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-custom-attributes) section mentioned that custom attribute types, the only options are `string` or `number`. I tried to force sending `true` or `false` but I got 400 response back.

**Comment by cgardens** [comment] 2020-06-16 04:05
@elorzafe - Thanks for your response!

I'm aware that Cognito only supports `string` and `number`. I am storing the string "true" in Cognito. When I retrieve it using amplify, amplify returns `true` (as a boolean) as opposed to "true" (as a string). I think the expectation should be that it returns the string "true" and doesn't perform a cast. 

The [line of code](https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/Auth.ts#L1926-L1940) I mentioned is where this unexpected cast happens. Let me know if this helps clarify!

**Comment by elorzafe** [comment] 2020-06-18 19:46
@cgardens you are correct on the behavior is strange. I found the problem on this [lines of code](https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/Auth.ts#L1985-L1992) 

I will discuss this with the team the fix for this, because it might be a breaking change if people is relying on this behavior.

**Closed** 2020-06-26 22:50 UTC
Labels: JavaScript, needs-discussion
