### ISSUE TITLE
Custom Style link is broken 

### ISSUE THREAD

**Issue by rafialikhan** [aws-amplify/docs#243] opened 2018-11-27 21:23 UTC
**Describe the bug**
When you click on the custom style default styles link it takes us to a 404 page.

**To Reproduce**
1. Go to 'https://aws-amplify.github.io/docs/js/angular'
2. Scroll down to 'Custom Styles'
3. Click on 'default styles'
4. See error (git hub 404 page)

**Expected behavior**
It should take the user to a valid blob at - https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-angular/src/theme.css

**Comment by nikhil-dabhade** [comment] 2018-12-06 18:21
@rafialikhan I can confirm that we are able to reproduce this issue. Thank you for pointing it out and apologies for the inconvenience. We are checking on this and will update you on the status this week.

**Comment by nikhil-dabhade** [comment] 2018-12-11 21:24
@rafialikhan : We are still working on this. We will keep you updated on when can we get this in by 12/14.

**Comment by nikhil-dabhade** [comment] 2019-01-02 16:47
@rafialikhan : Apologies for the delay on this (due to holiday season). We have this on our work log and will get to this by end of next week.

**Comment by jordanranz** [comment] 2019-06-07 17:08
The link is working. Closing this issue.

**Closed by jordanranz** 2019-06-07 17:08 UTC
Labels: JavaScript
