### ISSUE TITLE
[Feedback]Broken Link in Analytics Documentation

### ISSUE THREAD

**Issue by mechenault** [aws-amplify/docs#2135] opened 2020-07-20 21:52 UTC
**Page**: [`/lib/analytics/record/q/platform/js`](https://docs.amplify.aws/lib/analytics/record/q/platform/js)

**Feedback**:

Left side of the page under "Analytics" -> "Automatically track sessions" the link is broken.  It tries to load the below URL but gives a 404.

https://docs.amplify.aws/lib/analytics/autotrack/q/platform/js

**Comment by renebrandel** [comment] 2020-07-21 17:17
@mechenault - I can't reproduce this. Can you try again? Just to clarify you mean this button?
![image](https://user-images.githubusercontent.com/4989523/88085877-50f58c80-cb3b-11ea-88d2-da14ff05abec.png)

**Comment by mechenault** [comment] 2020-07-21 17:25
Yes that is the one.  I'm on a Mac and have replicated the problem in Firefox and Chrome.  Safari was able to load it though.  It is possibly some cacheing issues on my browsers after seeing that Safari loaded it.  I'd rather not blow away my entire cache for one page so I guess you can close this if you like.

Screen Recording of issue on Firefox.  Note the URL changes.  I do a ctrl + alt + R to refresh the page and that produces the 404 page.  https://youtu.be/oQ9wNfvTrRY

**Comment by mechenault** [comment] 2020-07-21 17:29
Just had another thought and disabled uBlock.  That allowed the page to load.  Turn back on uBlock and it's "broken" again.  Not sure why it was being blocked though.

**Comment by mauerbac** [comment] 2020-07-23 01:25
@mechenault - i'm unable to reproduce the issue as well. It sounds like it's related to a web browser extension. Going to close this.

**Closed by mauerbac** 2020-07-23 01:25 UTC
Labels: JavaScript
