### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by leungy2** [aws-amplify/docs#2322] opened 2020-08-28 15:31 UTC
**Page**: [`/guides/api-graphql/subscriptions-by-id/q/platform/ios`](https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/ios)

**Feedback**:

This is in JS. I really want just an example of what this would look like in Swift. Thanks

**Comment by palpatim** [comment] 2020-08-28 15:51
Dupe of https://github.com/aws-amplify/docs/issues/2323

(Technically this was filed first, but I saw the other one first :) )

**Closed by palpatim** 2020-08-28 15:51 UTC

**Comment by leungy2** [comment] 2020-08-28 16:05
Thanks so much for your help! Would really appreciate it if there's just
one example of how to pass in subscription arguments in Swift!
