### ISSUE TITLE
[missing-page] Ad Block Software Causes 404(ish)-Related Issue

### ISSUE THREAD

**Issue by harshvasoya008** [aws-amplify/docs#3052] opened 2021-03-15 16:51 UTC
**Page**: [`https://docs.amplify.aws/lib/analytics/autotrack/q/platform/android`](https://docs.amplify.aws/lib/analytics/autotrack/q/platform/android)

**Feedback**: 
Page under the header "Automatically track sessions" gives 404 page not found error. Kindly look into this.

**Comment by medelman17** [comment] 2021-03-15 23:36
Hi @harshvasoya008, can you provide the URL returning a 404? I can't seem to reproduce the above.

**Comment by harshvasoya008** [comment] 2021-03-16 09:30
Hi @medelman17, URL is https://docs.amplify.aws/lib/analytics/autotrack/q/platform/android
Try opening this URL in new tab and you will get 404.

**Comment by medelman17** [comment] 2021-03-16 15:10
@harshvasoya008, I tried accessing the page as you suggested, and, unfortunately, I still can't recreate the issue--it seems to work fine on my end. Are you having trouble accessing any other content on the site? 

<img width="943" alt="Screen Shot 2021-03-16 at 11 05 13 AM" src="https://user-images.githubusercontent.com/14793389/111332433-2915e480-8648-11eb-91b6-b0f770a7dc94.png">

**Comment by medelman17** [comment] 2021-03-29 21:53
After much hair-pulling, we've determined that the above issue arises from use of ad-blocking browser extensions in chrome. Specifically, it appears that because the URL above contains the phrase 'autotrack', the underlying resources needed to fully render the page are blocked client-side. As a result, the website errors out and kicks over to its 404 page. Disabling ad-blocking extensions resolves the problem. 

I am going to close this issue and open another to discuss wider implications and potential global fixes.

**Closed by medelman17** 2021-03-29 21:53 UTC
Labels: Bug, Docs Site (Itself)

**Comment by tjleing** [comment] 2021-04-08 21:38
Should be fixed now due to #3110 being merged in!  Please reopen if the problem persists 😄
