### ISSUE TITLE
Auth.forgotPasswordSubmit returns undefined in Nuxt Vue

### ISSUE THREAD

**Issue by berkaygurbuz** [aws-amplify/docs#3279] opened 2021-05-18 13:26 UTC
Auth.forgotPasswordSubmit returns undefined when you call this function. When I looked at the documentation  [AWS-Amplify Authentication](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#change-password), I saw this code and it returns data.

```
Auth.forgotPasswordSubmit(username, code, new_password)
    .then(data => console.log(data))
    .catch(err => console.log(err));
```

 But when I run my code, it returns undefined. I noticed that the password has changed even though this code returns undefined. I am not sure is it a feature or bug 😄

**Comment by chrisbonifacio** [comment] 2021-06-01 18:25
@medelman17 transferred over from js repo.

@berkaygurbuz wouldn't say this is either a bug or a feature lol rather than console logging `data`, could do something like this instead.

```js
Auth.forgotPasswordSubmit(state?.username, state?.code, state?.new_password)
      .then(() => console.log("password reset"))
      .catch((err) => console.log(err));
```

**Comment by berkaygurbuz** [comment] 2021-06-01 18:32
> @medelman17 transferred over from js repo.
> 
> @berkaygurbuz wouldn't say this is either a bug or a feature lol rather than console logging `data`, could do something like this instead.
> 
> ```js
> Auth.forgotPasswordSubmit(username, code, new_password)
>       .then(() => console.log("password reset"))
>       .catch((err) => console.log(err));
> ```

@chrisbonifacio 
I used it in a similar way. Your documents still seem to be returning data, which is causing confusion.

**Comment by medelman17** [comment] 2021-06-04 01:47
@chrisbonifacio -- Rather than include `console.log("password reset")` etc, let's remove all of the `then` bits in docs from auth APIs that do not return data. Thus, the above would look like: 

```
Auth.forgotPasswordSubmit(username, code, new_password).catch((err) => console.log(err));
```

Can you validate which of the bits return data and which (in addition to the `forgotPasswordSubmmit`) do not and need to be changed in a PR?

**Comment by sammartinez** [comment] 2021-09-22 15:58
Hey folks, for clarity here, the API is designed to return `undefined`. This is correct, please see this link to the [API documentation](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L1849). One thing to note here, there is a Hub event that is fired in order to ingest if you are needing to listen to the password reset event. Please see our [Hub documentation](https://docs.amplify.aws/lib/utilities/hub/q/platform/js/#listening-for-messages) on this. Since this is by design, I am going to resolve this issue. Please let us know if you have any other questions

**Closed by sammartinez** 2021-09-22 15:58 UTC
Labels: bug, JavaScript, Auth

**Comment by berkaygurbuz** [comment] 2021-09-22 22:12
@sammartinez When you look at the documentation of AWS Amplify, and read forgotPasswordSubmit, it seems like it returns data. API is correct, wrong is AWS Amplify documentation. Please check : [https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#change-password](AWS Amplify Documentation)
