### ISSUE TITLE
Can't initialise AWS Amplify for Android app in Android Studio

### ISSUE THREAD

**Issue by Phobez** [aws-amplify/docs#2693] opened 2020-11-23 04:01 UTC
**AWS Amplify Version**: 4.32.1

**Current Behaviour**:
I'm currently following the tutorial at https://docs.amplify.aws/start/getting-started/setup/q/integration/android. Everything works fine until the final part "Connect to the cloud" at https://docs.amplify.aws/start/getting-started/add-api/q/integration/android. When doing step 5 which is running the app, I get the following error:
```
AmplifyException {message=Failed to parse configuration JSON for AWS API Plugin, cause=AmplifyException {message=Failed to parse configuration, missing required key: endpoint, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Check amplifyconfiguration.json to make sure the AWS API configuration section hasn't been wrongly modified.}
        at com.amplifyframework.api.aws.AWSApiPluginConfigurationReader.parseConfigurationJson(AWSApiPluginConfigurationReader.java:97)
        at com.amplifyframework.api.aws.AWSApiPluginConfigurationReader.readFrom(AWSApiPluginConfigurationReader.java:56)
        at com.amplifyframework.api.aws.AWSApiPlugin.configure(AWSApiPlugin.java:127)
        at com.amplifyframework.core.category.Category.configure(Category.java:86)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:153)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:120)
        at com.example.todo.MyAmplifyApplication.onCreate(MyAmplifyApplication.java:18)
        at android.app.Instrumentation.callApplicationOnCreate(Unknown Source:0)
        at android.app.ActivityThread.handleBindApplication(Unknown Source:1209)
        at android.app.ActivityThread.access$1400(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(Unknown Source:710)
        at android.os.Handler.dispatchMessage(Unknown Source:19)
        at android.os.Looper.loop(Unknown Source:242)
        at android.app.ActivityThread.main(Unknown Source:98)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
        at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
     Caused by: AmplifyException {message=Failed to parse configuration, missing required key: endpoint, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.AWSApiPluginConfigurationReader.parseConfigurationJson(AWSApiPluginConfigurationReader.java:72)
        at com.amplifyframework.api.aws.AWSApiPluginConfigurationReader.readFrom(AWSApiPluginConfigurationReader.java:56) 
        at com.amplifyframework.api.aws.AWSApiPlugin.configure(AWSApiPlugin.java:127) 
        at com.amplifyframework.core.category.Category.configure(Category.java:86) 
        at com.amplifyframework.core.Amplify.configure(Amplify.java:153) 
        at com.amplifyframework.core.Amplify.configure(Amplify.java:120) 
        at com.example.todo.MyAmplifyApplication.onCreate(MyAmplifyApplication.java:18) 
        at android.app.Instrumentation.callApplicationOnCreate(Unknown Source:0) 
        at android.app.ActivityThread.handleBindApplication(Unknown Source:1209) 
        at android.app.ActivityThread.access$1400(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(Unknown Source:710) 
        at android.os.Handler.dispatchMessage(Unknown Source:19) 
        at android.os.Looper.loop(Unknown Source:242) 
        at android.app.ActivityThread.main(Unknown Source:98) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11) 
        at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
```

**Current Implementation**
Starting from https://docs.amplify.aws/start/getting-started/add-api/q/integration/android, I did the following steps:

- Run "amplify init" in the project's root directory in Android Studio
- Run "amplifyPush"
- Added the following code to MainActivity.java's onCreate method:

```
Amplify.DataStore.observe(Todo.class,
       started -> Log.i("Tutorial", "Observation began."),
       change -> Log.i("Tutorial", change.item().toString()),
       failure -> Log.e("Tutorial", "Observation failed.", failure),
       () -> Log.i("Tutorial", "Observation complete.")
);
```

**Expected Behaviour**:

It should work and I should see "Observation began." in the Logcat and the locally saved data should be pushed to the cloud backend.

**Comment by jamesonwilliams** [comment] 2020-11-23 05:28
Note for cross-reference: this issue also appears as [a StackOverflow question](https://stackoverflow.com/questions/64925267/cant-initialise-aws-amplify-for-android-app-in-android-studio).

**Comment by jamesonwilliams** [comment] 2020-11-23 06:38
I think part of the problem here is that the Guide talks about "Option 1" and "Option 2", but it isn't clear where the forked discussion ends, and where the main path rejoins.

I know that it happens [here](https://github.com/aws-amplify/docs/blame/322c529ba2357a844102a0f8b3bb6177e86d90fa/docs/lib/datastore/fragments/native_common/getting-started.md#L45):

> The base structure for a DataStore app is created by adding a new GraphQL API to your app.

However, when you quickly glance over the docs, there's no visual indication that that is the case.

**Comment by jpignata** [comment] 2020-11-24 16:08
@Phobez Were you able to successfully run the amplifyPush gradle command?

**Comment by Phobez** [comment] 2020-11-25 00:32
@jpignata Yes, I was. After that, I added the
```
Amplify.DataStore.observe(Todo.class,
       started -> Log.i("Tutorial", "Observation began."),
       change -> Log.i("Tutorial", change.item().toString()),
       failure -> Log.e("Tutorial", "Observation failed.", failure),
       () -> Log.i("Tutorial", "Observation complete.")
);
```
and ran the app on my device, and the logcat shows that it was unable to initialise Amplify.

**Comment by notentered** [comment] 2020-11-25 21:23
Just hit the same issue in almost the same context :)

What I did was to run the amplifyPush again. This time it took half an hour but it is OK now.

**Comment by Phobez** [comment] 2020-11-26 00:45
@notentered Did you do anything before running amplifyPush again? I'm going to try it the next time I can open the project.

**Comment by jamesonwilliams** [comment] 2020-11-26 00:48
I noticed that the [Getting Started docs (for CLI usage)](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android#option-2-use-amplify-cli) mention to run `amplify add api`, however, they **do not** mention the need to run `amplify push`.

I note that the [Getting Started guide for the API category](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/android#configure-api) **does** mention the need to run `amplify push`, explicitly.

Maybe this is the clarification that we need to make in the DataStore guide, @Phobez, @notentered?

**Comment by Phobez** [comment] 2020-11-26 01:53
@jamesonwilliams I did run amplifyPush but I was following https://docs.amplify.aws/start/getting-started/add-api/q/integration/android. Is this the same?

![image](https://user-images.githubusercontent.com/36761666/100298906-a94f0600-2fd5-11eb-9f6e-c2d069f5b1ec.png)

**Comment by jamesonwilliams** [comment] 2020-11-26 06:26
Ah, crumbs. [This section](https://docs.amplify.aws/start/getting-started/integrate/q/integration/android#configure-amplify-and-datastore) also says to include this line:
```kotlin
Amplify.addPlugin(AWSApiPlugin())
```
as a step _before_ adding a remote API. That's wrong, and will cause an error.

@jpignata has a draft up to fixup the Getting Started guide. Looks like the Guide has currently drifted from reality. @jpignata's changes should help.

https://github.com/aws-amplify/docs/pull/2711

**Comment by jpignata** [comment] 2020-12-01 16:08
Just merged these fixes. Thanks for the report!

**Comment by seriouscoderone** [comment] 2020-12-02 14:43
I tried the tutorial this morning. Still fails

```E/Tutorial: Could not initialize Amplify
    ApiException{message=Failed to parse configuration JSON for AWS API Plugin, cause=ApiException{message=Failed to parse configuration, missing required key: endpoint, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Check amplifyconfiguration.json to make sure the AWS API configuration section hasn't been wrongly modified.}
 ```

**Comment by jpignata** [comment] 2020-12-02 19:06
Working on this... Thank you, @seriouscoderone.

**Comment by jpignata** [comment] 2020-12-06 21:12
This should be resolved. A change in the CLI caused a regression that we had to do a new release to fix. Thanks again for this report!

**Closed by jpignata** 2020-12-06 21:12 UTC
Labels: Android, Getting Started
