### ISSUE TITLE
Authenticator component removes focus from input

### ISSUE THREAD

**Issue by Yazai** [aws-amplify/docs#4306] opened 2022-05-15 22:55 UTC
**Page**: [`/start/getting-started/auth/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/auth/q/integration/react)

**Feedback**:

Thank you for the example. But, as I work through with it, it seems not working properly.
When I put <Authenticator> tag to the example and type in to the todo title or desc, the app seems lose focus from the text box. (seems like refreshing every time when I type a character.)
If there is an error with the instruction, I am glad it it is fixed.

**Comment by Yazai** [comment] 2022-05-15 23:15
Seems the same issue with it https://github.com/aws-amplify/docs/issues/4037 , but it does not fix with npm update for @aws-amplify/ui-react.

**Comment by arundna** [comment] 2022-05-15 23:20
@Yazai - 👋 Thanks for reporting this issue and investigating the related issue that we had earlier. Can you check your package.json file for version of @aws-amplify/ui-react and also ensure that there are no multiple versions of the module installed?

**Comment by Yazai** [comment] 2022-05-17 23:26
Thank you for the comment. 
The ver in package.json is 2.17.1 > 2.9.0, and there seems is older version 1.2.9 but it is required by @aws-amplify\ui-react?
so I assumed it is ok. I will check my environment further.


xxx\AmplifyHandsOn\react-amplified\package.json(6,6)  [UTF-8]:     "@aws-amplify/ui-react": "^2.17.1"
xxx\AmplifyHandsOn\react-amplified\node_modules\@aws-amplify\ui-react\node_modules\@aws-amplify\ui-react-v1\package.json(3,11)  [UTF-8]:   "_id": "@aws-amplify/ui-react@1.2.9",

**Comment by arundna** [comment] 2022-05-18 18:51
Ah, it could be due to the conflicting versions of the `@aws-amplify/ui-react` packages. Can you please remove the 1.2.9 version and let me know if you still face an issue?

**Comment by Yazai** [comment] 2022-05-20 22:38
I am trying out amplify and new to JavaScript or react, so plz correct me if I am wrong.

I think the older version of @aws-amplify/ui-react(the 1.2.9 version) "ui-react-v1" is required by aws-amplify package(@aws-amplify/ui-react@2.18.1). Is there a way to fix it by a module user?

The code may be here...

xxx\AmplifyHandsOn\react-amplified\node_modules\@aws-amplify\ui-react\dist\legacy.js

`export{AmplifyAuthenticator,AmplifyChatbot,AmplifyPhotoPicker,AmplifyPicker,AmplifyS3Album,AmplifyS3Image,AmplifyS3ImagePicker,AmplifyS3Text,AmplifyS3TextPicker,AmplifySignIn,AmplifySignOut,withAuthenticator}from"@aws-amplify/ui-react-v1";
`

xxx\AmplifyHandsOn\react-amplified\node_modules\@aws-amplify\ui-react\dist\esm\legacy.js

`withAuthenticator, } from '@aws-amplify/ui-react-v1';`


```
 npm ls aws-amplify 
react-amplified@0.1.0 xxx\AmplifyHandsOn\react-amplified
├─┬ @aws-amplify/ui-react@2.18.1
│ ├─┬ @aws-amplify/ui-react-v1@npm:@aws-amplify/ui-react@1.2.9
│ │ └─┬ @aws-amplify/ui-components@1.7.2
│ │   └── aws-amplify@4.3.22 deduped
│ ├─┬ @aws-amplify/ui@3.9.1
│ │ └── aws-amplify@4.3.22 deduped
│ └── aws-amplify@4.3.22 deduped
└── aws-amplify@4.3.22
```

**Comment by arundna** [comment] 2022-05-30 03:59
@Yazai - Apologies for the delayed response. You are right and I double checked my @aws-amplify/ui-react version which was `2.15.1` and the reason it worked. I tested it on `2.17.1` `2.18.1` and also the latest version `2.18.3` and was able to successfully reproduce the issue where the focus is lost on each character typed.

It appears that this is a regression of https://github.com/aws-amplify/amplify-ui/issues/1451. I'll reach out to the team and keep you posted with further updates.

**Comment by ErikCH** [comment] 2022-05-31 18:56
Thanks @arundna and @Yazai ! I was able to reproduce, and I'm testing a fix now.

**Comment by ErikCH** [comment] 2022-06-01 21:22
I went ahead and merged in a fix to the docs. So please, wrap your app in `withAuthenticator`. This is the proper way of using our Authenticator.

**Closed by ErikCH** 2022-06-01 21:22 UTC
Labels: amplify/ui, p2
