### ISSUE TITLE
Suggest CI/CD workflows for iOS & Android customers

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/docs#2715] opened 2020-11-27 22:00 UTC
Currently, the `.gitignore` generated by the Amplify CLI intentionally excludes `awsconfiguration.json` and `amplifyconfiguration.json` files, by design. This is done so that users _opt-in_ to committing these files. Depending on what has been configured, and the security posture of the customer's application, these files may contain information that is **not** suitable to store on disk in a repo.

Great. Cool. Fine.

However, where _should_ the customer put them, then? And how does the application under test access them, so that tests can be invoked?

These questions arise for customers building out production CI/CD pipelines. The Amplify documentation should include guidance on who to securely store, access, and bundle configurations in a popular CI/CD runtime.

Reference: https://github.com/aws-amplify/amplify-android/discussions/1005#discussioncomment-140264
cc: @bpappin

**Comment by bpappin** [comment] 2020-11-30 15:08
Even more importantly, include documentation about how to deploy an application without these files. They are not included in the APK, but the library looks for them, and fails if they are not there (as in the case of them being ignored by .gitignore)

**Comment by eeatonaws** [comment] 2022-06-09 19:37
Duplicate of #4382

**Closed by eeatonaws** 2022-06-09 19:37 UTC
Labels: feature-request, amplify/ios, amplify/android, information-architecture, p4
