### ISSUE TITLE
AmplifyTOTPSetup broken code snippet

### ISSUE THREAD

**Issue by HarrisonJackson** [aws-amplify/docs#2678] opened 2020-11-20 07:04 UTC
**Page**: [`/ui/auth/authenticator/q/framework/react`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#slots)

**Feedback**:

Broken code snippet
```
<AmplifyAuthenticator>
  <AmplifyTOTPSetup
    headerText="My Custom TOTP Setup Text"
    slot="totp-setup"
  ></AmplifyTOTPSetup>
</AmplifyAuthenticator>
```

The react component is `AmplifyTotpSetup` not `AmplifyTOTPSetup` and using this component causes the QR code to render a broken image. Related issue https://github.com/aws-amplify/amplify-js/issues/7241

**Comment by nonbeing** [comment] 2021-02-02 12:37
+1

Confirmed at my end too - it should be `AmplifyTotpSetup` instead of `AmplifyTOTPSetup`.

In fact, if you even try to:

```
import {  AmplifyTOTPSetup } from '@aws-amplify/ui-react'
```
it will fail because it's not found in `@aws-amplify/ui-react`. 

Please have this fixed.

**Comment by sammartinez** [comment] 2021-05-17 22:47
We have changed the Code snippet to reflect the above. Resolving this issue. Thanks for reporting this!

**Closed by sammartinez** 2021-05-17 22:47 UTC
Labels: JavaScript
