### ISSUE TITLE
Objective-C Sample Code Needed

### ISSUE THREAD

**Issue by Stunner** [aws-amplify/docs#934] opened 2019-09-24 02:23 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there are **only** *Swift* code samples provided from large companies. As if *Objective-C* is no longer in existence. This lack of documentation for the legacy version of a coding language is something typically seen in startups. As a maintainer for your SDKs its imperative to have as little friction for a new user as possible. I am speaking from experience (I too have maintained an SDK in the past.)

**Describe the solution you'd like**
*Objective-C* code samples.

**Describe alternatives you've considered**
Your competitors in the mobile analytics space, namely Firebase Analytics and Mixpanel.

See: https://aws-amplify.github.io/docs/ios/analytics for an example of what I am referring to.

**Comment by palpatim** [comment] 2019-09-24 13:41
Dupe of https://github.com/aws-amplify/docs/issues/641, but tagging @nikhil-dabhade to provide a response for this

**Comment by swaminator** [comment] 2020-06-15 23:29
@Stunner we do not currently have plans to support Obj C with the Amplify Library. Please open a feature request on the https://github.com/aws-amplify/amplify-ios/issues to see if there are a lot of other community members with similar requests.

**Closed by swaminator** 2020-06-15 23:29 UTC
Labels: feature-request, iOS SDK
