### ISSUE TITLE
Gen2 Data custom subscriptions page does not load in Chrome

### ISSUE THREAD

**Issue by david-mcafee** [aws-amplify/docs#7919] opened 2024-08-27 19:22 UTC
**Describe the bug**

Gen2 Data custom subscriptions page does not load in Chrome, but works in Safari.

**To Reproduce**
1. Go to https://docs.amplify.aws/react/build-a-backend/data/custom-subscription/
2. Page is empty
3. Open console, note the following errors:

```bash
This document requires 'TrustedHTML' assignment.
```

```bash
Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
```

```bash
This document requires 'TrustedScriptURL' assignment.
```

```bash
Uncaught TypeError: Failed to set the 'src' property on 'HTMLScriptElement': This document requires 'TrustedScriptURL' assignment.
```

```bash
main-a75043fc474be08e.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

```bash
Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

**Expected behavior**
The page should load as expected.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Chrome version 127.0.6533.122

**Smartphone (please complete the following information):**

**Additional context**

**Comment by esauerbo** [comment] 2024-08-27 20:41
This was caused by commit https://github.com/aws-amplify/docs/commit/a11a9e0af4962c81fdc5fb81d171dd868c1d1c69, which was reverted in https://github.com/aws-amplify/docs/commit/4f081f728f6a7b0fa67367ec38e1a85986962eaa. The page is fixed now so closing this out.

**Closed by esauerbo** 2024-08-27 20:41 UTC
Labels: bug, amplify/docs-engineering, p1, API GraphQL
