### ISSUE TITLE
JS Getting Started Tutorial linking to Flutter UI components

### ISSUE THREAD

**Issue by rachelnabors** [aws-amplify/docs#4666] opened 2022-10-06 18:14 UTC
**Describe the bug**
On the JS Getting Started Tutorial landing page, if I click "UI Components", I'm taken to the Flutter UI Components page.

**To Reproduce**
1. Go to [JS Getting Started Tutorial landing page](https://docs.amplify.aws/start/q/integration/js/)
2. Click on UI Components
4. See "Flutter" is now chosen in the platform picker

**Expected behavior**
JS should still be chosen in the platform picker

**Screenshots**
Before
![Screen Shot 2022-10-06 at 11 13 26 AM](https://user-images.githubusercontent.com/236306/194388048-c7329791-d1b4-477b-b438-7a3fbd76e436.png)

After
![Screen Shot 2022-10-06 at 11 13 16 AM](https://user-images.githubusercontent.com/236306/194388068-0190b219-f2f5-41a0-b743-5ca118cffd96.png)

**Comment by salihgueler** [comment] 2022-10-09 10:35
The issue happens because of not Flutter but the page keeps the latest platform selection for the UI page. 

Steps to reproduce:

- Fork the library and run the project
- Go to JS getting started guide 
- Click on the UI libraries it will take you to select a platform / JS Does not exist there
- Select a platform 
- Go back to the getting started guide 
- Select JS again
- Click on the UI components, it will take you to the latest selected UI components page

**Comment by rachelnabors** [comment] 2022-10-09 14:49
I end up in the Vue page when I attempt to repro through your steps.

An alternative would be to link to Amplify UI's site directly, since these
pages are legacy.

**Comment by reesscot** [comment] 2024-02-08 22:34
This was fixed in the latest version of the Amplify Docs

**Closed by reesscot** 2024-02-08 22:34 UTC
Labels: good first issue, amplify/docs-engineering, p2, submitted
