### ISSUE TITLE
Recycle query predicate docs for both API and DataStore categories

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/docs#2228] opened 2020-08-12 05:29 UTC
### Issue

The DataStore documentation includes notes on querying data by means of filtering predicates. This is true of both [iOS](https://docs.amplify.aws/lib/datastore/data-access/q/platform/ios#predicates) and [Android](https://docs.amplify.aws/lib/datastore/data-access/q/platform/android#predicates).

The API category uses the same query predicates for filtering on _its_ query API. However, the API (GraphQL) documentation mentions nothing about the ability to query with filtering predicates. This is also true of both [iOS](https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/ios) and [Android](https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/android).

### Describe the solution you'd like

The API (GraphQL) category documentation for iOS and Android should include notes on using query predicates. Ideally, this documentation could largely be recycled (perhaps by a fragment include) from that already surfaced in the DataStore documentation.

### Describe alternatives you've considered

Cloning some of the contents of [`lib/datastore/data-access.md`](https://github.com/aws-amplify/docs/blame/master/docs/lib/datastore/data-access.md#L29) into [`lib/graphqlapi/query-data.md`](https://github.com/aws-amplify/docs/blame/master/docs/lib/graphqlapi/query-data.md#L5), without creating any shared fragment between the categories.

### Additional Context

I have successfully navigated API (GraphQL) users to the predicate documentation in DataStore, and they have confirmed that this same documentation is useful in forming queries to the GraphQL query API.

------------------------

cc: @richardmcclellan @drochetti

**Comment by eeatonaws** [comment] 2022-06-09 19:33
Duplicate of #4381

**Closed** 2022-06-09 19:33 UTC
Labels: good first issue, amplify/ios, amplify/android, p4
