### ISSUE TITLE
[Feedback] Page title doesn't provide enough information to users (and crawlers)

### ISSUE THREAD

**Issue by atrasatti** [aws-amplify/docs#5265] opened 2023-03-18 01:04 UTC
**Page**: [`/ChooseFilterPage`](https://docs.amplify.aws/lib/pubsub/getting-started)

**Feedback**:
I noticed there are a number of pages such as the above one where the page title (<title> tag in HTML) is just "Getting Started". Clicking on one of the platforms, such as JavaScript, provides a much more meaningful title. Providing a better page title would likely help users who are for example searching on Google to understand what the page is about.

I would suggest some simple text concatenation, looking at the page above, something as simple as "Getting Started with <topic>, choose <platform 1>, <platform n> - AWS Amplify Docs".

Alternatively you could use a concatenation similar to how it appears in https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/react-native/, i.e. "<topic> - Getting Started - Pick a platform - AWS Amplify Docs". You don't want to make the title too long so this might be a better string.

**Comment by rachelnabors** [comment] 2023-03-29 00:23
Possible dupe of https://github.com/aws-amplify/docs/issues/5162

Seems like we can handle this!

**Comment by lavr001** [comment] 2023-06-14 18:14
Changed a title prop in the ChooseFilterPage.tsx file to ${chapterTitle} - ${title} - Choose a platform to make it more descriptive and consistent with other sub tabs titles. Updated title is within recommended 60-70 characters length for SEO's purposes.

**Closed by lavr001** 2023-06-14 18:14 UTC
Labels: amplify/docs-engineering, p3
