### ISSUE TITLE
Code snippet not refreshing when changing from iOS to Android 

### ISSUE THREAD

**Issue by elorzafe** [aws-amplify/docs#2405] opened 2020-09-16 22:08 UTC
**Describe the bug**
Code snippet remains on the first loaded platform when switching using the Framework list to move the iOS to Android and viceversa

**To Reproduce**
1. Go to https://docs.amplify.aws/lib/auth/password_management/q/platform/ios
2. Click on the left button to and select Android

Code snippet will be the iOS one. Refreshing the page fix it.

**Expected behavior**
Show the correct code snippet when switching from iOS to Android and viceversa

**Screenshots**
![image](https://user-images.githubusercontent.com/28815678/93397370-56ffa500-f82e-11ea-9739-b472265adaaf.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Chrome
 - Version 85

**Comment by mauerbac** [comment] 2020-09-18 15:44
Thanks for reporting @elorzafe . I was able to reproduce. Marking this a docs eng task. Thank you

**Comment by tjleing** [comment] 2020-10-23 20:02
PR merged, and the issue is fixed in live.

**Closed by tjleing** 2020-10-23 20:02 UTC
Labels: Bug, Docs Site (Itself)
