### ISSUE TITLE
broken link in DataStore docs

### ISSUE THREAD

**Issue by phishy** [aws-amplify/docs#1093] opened 2020-01-09 20:05 UTC
**Describe the bug**

At URL: https://aws-amplify.github.io/docs/js/datastore, the link at the bottom that reads the following is broken.

`For the complete API documentation for DataStore, visit our API Reference`

**Comment by sammartinez** [comment] 2020-01-10 16:31
@phishy Thank you for bringing this to our attention, we are looking to have this be prioritized in order to resolve this bug. We will let you know when there is a PR for this fix. Thanks

**Comment by Amplifiyer** [comment] 2020-01-10 21:13
Duplicate of https://github.com/aws-amplify/amplify-js/issues/4604. We are working on this issue. Closing this, please followup on the related issue.

**Closed by Amplifiyer** 2020-01-10 21:13 UTC
Labels: JavaScript, bug
