### ISSUE TITLE
[Feedback]FEEDBACK_TITLE_HERE

### ISSUE THREAD

**Issue by AvinandanBandyopadhyay** [aws-amplify/docs#4473] opened 2022-07-22 12:36 UTC
**Page**: [`/start/getting-started/nextsteps/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/react)

**Feedback**:

export 'AmplifyChatbot' (imported as 'AmplifyChatbot') was not found in '@aws-amplify/ui-react' (possible exports: Alert, AmplifyProvider, Authenticator, Badge, Button, ButtonGroup, Card, CheckboxField, Collection, ComponentClassNames, ComponentClassObject, ComponentPropsToStylePropsMap, ComponentPropsToStylePropsMapKeys, Divider, Expander, ExpanderItem, FieldGroupIcon, FieldGroupIconButton, Flex, Geocoder, Grid, Heading, Icon, Image, Link, Loader, LocationSearch, MapView, Menu, MenuButton, MenuItem, Pagination, PasswordField, PhoneNumberField, Placeholder, Radio, RadioGroupField, Rating, ScrollView, SearchField, SelectField, SliderField, StepperField, SwitchField, TabItem, Table, TableBody, TableCell, TableFoot, TableHead, TableRow, Tabs, Text, TextAreaField, TextField, ThemeProvider, ToggleButton, ToggleButtonGroup, View, VisuallyHidden, components, createTheme, defaultDarkModeOverride, defaultTheme, primitives, translations, useAmplify, useAuthenticator, useBreakpointValue, usePagination, useTheme, withAuthenticator)

**Comment by siegerts** [comment] 2022-07-25 13:47
closing as duplicate of https://github.com/aws-amplify/docs/issues/4474

**Closed by siegerts** 2022-07-25 13:47 UTC
Labels: amplify/ui
