### ISSUE TITLE
[Feedback]WINDOWS TUTORIAL

### ISSUE THREAD

**Issue by Gurleen28** [aws-amplify/docs#5183] opened 2023-03-02 03:55 UTC
**Page**: [`/start/getting-started/setup/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/setup/q/integration/js)

**Feedback**:

It would be nice to have a guide for windows as well.

**Comment by abdallahshaban557** [comment] 2023-05-05 17:45
Closing this as a duplicate of #5053

**Closed by abdallahshaban557** 2023-05-05 17:45 UTC
Labels: amplify/cli, amplify/js, p3
