### ISSUE TITLE
(Android) Cognito Hosted UI : After uninstall - credentials are not removed

### ISSUE THREAD

**Issue by narindermalik2** [aws-amplify/docs#753] opened 2019-06-25 11:36 UTC
**Describe the bug**
I am using cognito hosted UI. Once user has logged in using the right credentials and then uninstall the app, ideally the credentials should be removed. Currently, if the user reinstall the app, he gets logged in without asking for the credentials. That means the credentials were not removed during uninstall or even reinstall.

**To Reproduce**
1. Create app using cognito hosted UI
2. login into the app using credentials
3. Uninstall the app
4. Install again
5. try to login
6. ideally, it should ask for credentails (as the app was uninstalled) but it logins successfully without credentials

**Expected behavior**
After reinstall, credentials should be required again.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: android
 - OS: N/A
 - Version : N/A

**Comment by palpatim** [comment] 2019-06-25 14:54
This issue seems to be a duplicate of https://github.com/aws-amplify/aws-sdk-android/issues/940, so I'm closing it. If you believe the behavior you're seeing is not the same as described in the [previous issue](https://github.com/aws-amplify/aws-sdk-android/issues/940) please open a new issue on the [SDK issues page](https://github.com/aws-amplify/aws-sdk-android/issues/). This repo is for SDK documentation.

**Closed by palpatim** 2019-06-25 14:54 UTC
