### ISSUE TITLE
Dependency issues when installing aws-amplify@3.0.24

### ISSUE THREAD

**Issue by BastianMuc** [aws-amplify/docs#2496] opened 2020-08-22 21:02 UTC
**Describe the bug**
When installing aws-amplify from scratch in a new React project, I'm getting dependency issues to @react-native-community/netinfo@^5.5.0 and react-native@>=0.56:

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/54812629/90965671-9276b000-e4ca-11ea-9da3-caf5bd3731e8.png">

**To Reproduce**

1) Create new react app via `npx create-react-app xyz`
2) `cd xyz`
3) `npm install aws-amplify`

**Expected behavior**
aws-amplify installed without dependency errors.

```
  System:
    OS: Linux 4.14 Amazon Linux AMI 2018.03
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
    Memory: 379.91 MB / 1.91 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
  npmPackages:
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.5.0 => 9.5.0 
    @testing-library/user-event: ^7.2.1 => 7.2.1 
    aws-amplify: ^3.0.24 => 3.0.24 
    react: ^16.13.1 => 16.13.1 
    react-dom: ^16.13.1 => 16.13.1 
    react-scripts: 3.4.3 => 3.4.3 
    semantic-ui-react: ^1.2.1 => 1.2.1 
    typescript: ^4.0.2 => 4.0.2 
  npmGlobalPackages:
    @aws-amplify/cli: 4.27.3
    cdk: 1.59.0
    coffeescript: 2.5.1
    esformatter: 0.11.3
    inquirer: 7.3.3
    js-beautify: 1.12.0
    npm: 6.14.6
    prettier: 2.0.5
    typescript: 3.7.5
```

</details>

**Comment by sammartinez** [comment] 2020-10-05 16:22
Testing this out, I am getting the same behavior. @Ashish-Nanda and @amhinson is this normal for us to have the peer dependency for React Native show up when installing an React project?

**Comment by amhinson** [comment] 2020-10-05 16:27
Yes, this is expected behavior right now since React and React Native share the same packages, and using Amplify with React Native requires additional peer dependencies.

**Comment by sammartinez** [comment] 2020-10-05 16:43
Thanks for the update on this @amhinson. @BastianMuc As @amhinson has stated this is expected behavior currently. Resolving

**Closed by sammartinez** 2020-10-05 16:43 UTC
Labels: JavaScript
