### ISSUE TITLE
I18n not translating all phrases in authenticator

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/docs#501] opened 2019-02-27 22:38 UTC
**Describe the bug**
When using I18n putVocabularies(dict) not all phrases in dict are translated in the Authenticator.

**To Reproduce**
1. Enable I18n in a Vue App:
```
Vue.use(AmplifyPlugin, AmplifyModules)
const dict = {
  'no-nb': {
    'No account?': 'Ikke bruker?', // Works fine
    'Create account': 'Opprett bruker' // Not translated!
  }
}
AmplifyModules.I18n.putVocabularies(dict)
AmplifyModules.I18n.setLanguage('no-nb')
```
2. Observe the login form resulting from ```<amplify-authenticator :auth-config="authConfig" />```

**Expected behavior**
Both phrases should be translated. Similar errors happens in the sign-up form. ex: Have an account? will not be translated.

**Comment by manueliglesias** [comment] 2019-03-22 22:59
Duplicate of aws-amplify/amplify-js#2875

**Closed by manueliglesias** 2019-03-22 22:59 UTC
Labels: JavaScript
