### ISSUE TITLE
[Feedback] Auth error 

### ISSUE THREAD

**Issue by pborokh** [aws-amplify/docs#4037] opened 2022-02-13 01:37 UTC
**Page**: [`/start/getting-started/auth/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/auth/q/integration/react/#create-login-ui)

**Feedback**:

after adding Authentication the form stops to work as onChange fires after every character input then Authenticator removes focus from the input

**Comment by ToreMalibu** [comment] 2022-03-12 22:03
I've done it 3 times and everything works until you add "auth" - in my console I get an error wanting to now if I ran a "amplify push" - which is exactly what the tutorial tells you to do - push - does anyone know a workaround or hack or whatever to et this working?

**Comment by arundna** [comment] 2022-03-18 17:22
@pborokh - 👋  Thanks for reporting this issue! I was able to reproduce this and related to the Authenticator component.

This is tracked here - [aws-amplify/amplify-ui#1451](https://github.com/aws-amplify/amplify-ui/issues/1451) and fixed with ui-react version 2.9.0 onwards. 

Please update your dependency for the fix by running `npm install @aws-amplify/ui-react` and that should resolve the issue. 

Closing this in as the issue is fixed as a bug on UI. Feel free to re-open the issue if you need further assistance. Thanks!

**Closed** 2022-03-18 17:22 UTC
Labels: bug, amplify/ui, auth

**Comment by pborokh** [comment] 2022-03-18 17:24
Thank you!
